from __future__ import annotations


LITERATURE_CHALLENGE_DAYS = [
    {
        "day": 1,
        "title": "DAY 1",
        "tasks": [
            {
                "code": "literature_day1_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "소설가 구보 씨의 일일",
                "importance": "AA",
                "genre": "현대소설",
                "author": "박태원",
                "textbook": "수능특강",
                "page": 164,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/watch?v=E9d0_v8XAMk",
                "order": 1,
            },
            {
                "code": "literature_day1_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "하나씩의 별",
                "importance": "AA",
                "genre": "현대시",
                "author": "이용악",
                "textbook": "수능특강",
                "page": 32,
                "series": "홍준석 현대시",
                "video_url": "https://www.youtube.com/watch?v=lpIiNbhXu-U",
                "order": 2,
            },
        ],
    },
    {
        "day": 2,
        "title": "DAY 2",
        "tasks": [
            {
                "code": "literature_day2_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "서해무릉기",
                "importance": "AA",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 125,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/shorts/sfAl64gBpEM",
                "order": 1,
            },
            {
                "code": "literature_day2_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "면앙정가",
                "importance": "AA",
                "genre": "고전시가",
                "author": "송순",
                "textbook": "수능특강",
                "page": 58,
                "series": "10 CUT",
                "video_url": "https://www.youtube.com/watch?v=iRdBKJcVg-E",
                "order": 2,
            },
        ],
    },
    {
        "day": 3,
        "title": "DAY 3",
        "tasks": [
            {
                "code": "literature_day3_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "줄",
                "importance": "AA",
                "genre": "현대소설",
                "author": "이청준",
                "textbook": "수능완성",
                "page": 52,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/watch?v=sttxD12MlQA",
                "order": 1,
            },
            {
                "code": "literature_day3_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "눈 오는 날에",
                "importance": "AA",
                "genre": "현대시",
                "author": "조지훈",
                "textbook": "수능특강",
                "page": 99,
                "series": "홍준석 현대시",
                "video_url": "https://www.youtube.com/watch?v=iDAAQBzgMHU",
                "order": 2,
            },
        ],
    },
    {
        "day": 4,
        "title": "DAY 4",
        "tasks": [
            {
                "code": "literature_day4_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "반씨전",
                "importance": "AA",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 129,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/shorts/KE4ljgx9l6o",
                "order": 1,
            },
            {
                "code": "literature_day4_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "속사미인곡",
                "importance": "AA",
                "genre": "고전시가",
                "author": "이진유",
                "textbook": "수능특강",
                "page": 67,
                "series": "10 CUT",
                "video_url": "https://www.youtube.com/watch?v=1w7epBOJIrs",
                "order": 2,
            },
        ],
    },
    {
        "day": 5,
        "title": "DAY 5",
        "tasks": [
            {
                "code": "literature_day5_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "현몽쌍룡기",
                "importance": "AA",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 133,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/watch?v=PVO7dqFcwYU",
                "order": 1,
            },
            {
                "code": "literature_day5_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "목계장터",
                "importance": "AA",
                "genre": "현대시",
                "author": "신경림",
                "textbook": "수능완성",
                "page": 45,
                "series": "홍준석 현대시",
                "video_url": "https://www.youtube.com/watch?v=PKUiWd7UVYM",
                "order": 2,
            },
        ],
    },
    {
        "day": 6,
        "title": "DAY 6",
        "tasks": [
            {
                "code": "literature_day6_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "금환기봉",
                "importance": "AA",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 322,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/shorts/f_-HHL6M9YQ",
                "order": 1,
            },
            {
                "code": "literature_day6_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "백석정별곡",
                "importance": "AA",
                "genre": "고전시가",
                "author": "신교",
                "textbook": "수능특강",
                "page": 75,
                "series": "10 CUT",
                "video_url": "https://www.youtube.com/watch?v=CgkLuUDXxgk",
                "order": 2,
            },
        ],
    },
    {
        "day": 7,
        "title": "DAY 7",
        "tasks": [
            {
                "code": "literature_day7_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "창선감의록",
                "importance": "AA",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능완성",
                "page": 146,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/watch?v=Z4ycfFMtlas",
                "order": 1,
            },
            {
                "code": "literature_day7_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "합강정가",
                "importance": "AA",
                "genre": "고전시가",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 244,
                "series": "10 CUT",
                "video_url": "https://www.youtube.com/watch?v=cIE2ccPUGX4",
                "order": 2,
            },
        ],
    },
    {
        "day": 8,
        "title": "DAY 8",
        "tasks": [
            {
                "code": "literature_day8_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "인간 문제",
                "importance": "A",
                "genre": "현대소설",
                "author": "강경애",
                "textbook": "수능특강",
                "page": 169,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/shorts/_99tmdb_lcY",
                "order": 1,
            },
            {
                "code": "literature_day8_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "눈",
                "importance": "AA",
                "genre": "현대시",
                "author": "김수영",
                "textbook": "수능완성",
                "page": 200,
                "series": "홍준석 현대시",
                "video_url": "https://www.youtube.com/watch?v=OJieJbO1v10",
                "order": 2,
            },
            {
                "code": "special",
                "type": "literature_video",
                "content_type": "special",
                "title": "한씨 연대기",
                "importance": "AA",
                "genre": "극·수필",
                "author": "황석영 원작 · 김석만·오인두 각색",
                "textbook": "수능완성",
                "page": 77,
                "series": "EBS / 작품 해설",
                "video_url": "https://www.youtube.com/watch?v=H_0Y57GRFLU",
                "order": 3,
            },
        ],
    },
    {
        "day": 9,
        "title": "DAY 9",
        "tasks": [
            {
                "code": "literature_day9_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "임진록",
                "importance": "A",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 20,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/watch?v=8rJQsGXNo4c",
                "order": 1,
            },
            {
                "code": "literature_day9_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "만흥",
                "importance": "AA",
                "genre": "고전시가",
                "author": "윤선도",
                "textbook": "수능완성",
                "page": 60,
                "series": "10 CUT",
                "video_url": "https://www.youtube.com/watch?v=42OPXLtmPQ4",
                "order": 2,
            },
        ],
    },
    {
        "day": 10,
        "title": "DAY 10",
        "tasks": [
            {
                "code": "literature_day10_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "치숙",
                "importance": "A",
                "genre": "현대소설",
                "author": "채만식",
                "textbook": "수능특강",
                "page": 173,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/watch?v=ApYaz5VmGPw",
                "order": 1,
            },
            {
                "code": "literature_day10_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "흰 바람벽이 있어",
                "importance": "AA",
                "genre": "현대시",
                "author": "백석",
                "textbook": "수능완성",
                "page": 151,
                "series": "홍준석 현대시",
                "video_url": "https://www.youtube.com/watch?v=LIaJFKYwaHQ",
                "order": 2,
            },
        ],
    },
    {
        "day": 11,
        "title": "DAY 11",
        "tasks": [
            {
                "code": "literature_day11_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "금방울전",
                "importance": "A",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 142,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/shorts/ppucL-yWbo4",
                "order": 1,
            },
            {
                "code": "literature_day11_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "쉽게 씌어진 시",
                "importance": "AA",
                "genre": "현대시",
                "author": "윤동주",
                "textbook": "수능완성",
                "page": 223,
                "series": "홍준석 현대시",
                "video_url": "https://www.youtube.com/watch?v=V3TEv5Sudg4",
                "order": 2,
            },
        ],
    },
    {
        "day": 12,
        "title": "DAY 12",
        "tasks": [
            {
                "code": "literature_day12_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "고향",
                "importance": "A",
                "genre": "현대소설",
                "author": "이기영",
                "textbook": "수능특강",
                "page": 330,
                "series": "2027 수능특강 짧은 해설",
                "video_url": "https://www.youtube.com/watch?v=_lD4P8_dJrc",
                "note": "현진건 「고향」이 아니라 이기영 「고향」",
                "order": 1,
            },
            {
                "code": "literature_day12_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "부여노정기",
                "importance": "AA",
                "genre": "고전시가",
                "author": "연안 이씨",
                "textbook": "수능특강",
                "page": 308,
                "series": "2027 수능특강 짧은 해설",
                "video_url": "https://www.youtube.com/watch?v=UY1nXbVf9eQ",
                "order": 2,
            },
        ],
    },
    {
        "day": 13,
        "title": "DAY 13",
        "tasks": [
            {
                "code": "literature_day13_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "적벽가",
                "importance": "A",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 146,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/watch?v=Unk3ka9kjNI",
                "order": 1,
            },
            {
                "code": "literature_day13_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "꽃",
                "importance": "A",
                "genre": "현대시",
                "author": "이육사",
                "textbook": "수능특강",
                "page": 90,
                "series": "홍준석 현대시",
                "video_url": "https://www.youtube.com/watch?v=G6RyzGOJYMU",
                "order": 2,
            },
        ],
    },
    {
        "day": 14,
        "title": "DAY 14",
        "tasks": [
            {
                "code": "literature_day14_novel",
                "type": "literature_video",
                "content_type": "novel",
                "title": "인현왕후전",
                "importance": "A",
                "genre": "고전소설",
                "author": "작자 미상",
                "textbook": "수능특강",
                "page": 262,
                "series": "U미니극장",
                "video_url": "https://www.youtube.com/shorts/nMRkYiOV9qE",
                "order": 1,
            },
            {
                "code": "literature_day14_poetry",
                "type": "literature_video",
                "content_type": "poetry",
                "title": "월곡답가",
                "importance": "A",
                "genre": "고전시가",
                "author": "정훈",
                "textbook": "수능특강",
                "page": 51,
                "series": "10 CUT",
                "video_url": "https://www.youtube.com/watch?v=3gApUssXZf8",
                "order": 2,
            },
        ],
    },
]
