from __future__ import annotations


FORMULA_QUIZ_EXPECTED_COUNT = 30


DAY1_FORMULA_QUIZ_ITEMS = [
    {
        "code": "d1_exp_log_01",
        "day": 1,
        "subject": "math1",
        "chapter": "지수와 로그",
        "concept_code": "d1_math1_1_4_지수법칙_곱",
        "type": "multiple_choice",
        "prompt": "같은 밑의 거듭제곱에 대하여 \\(a^m \\times a^n\\)과 같은 것은?",
        "choices": ["\\(a^{mn}\\)", "\\(a^{m+n}\\)", "\\(a^{m-n}\\)", "\\(a^{m/n}\\)"],
        "answer_index": 1,
        "explanation": "밑이 같고 곱셈이면 지수를 더해 \\(a^{m+n}\\)으로 계산합니다.",
    },
    {
        "code": "d1_exp_log_02",
        "day": 1,
        "subject": "math1",
        "chapter": "지수와 로그",
        "concept_code": "d1_math1_1_3_a_n",
        "type": "multiple_choice",
        "prompt": "\\(a\\neq0\\)일 때 \\(a^{-3}\\)과 같은 것은?",
        "choices": ["\\(-a^3\\)", "\\(\\frac{1}{a^3}\\)", "\\(\\frac{1}{3a}\\)", "\\(a^3\\)"],
        "answer_index": 1,
        "explanation": "음의 지수는 역수를 뜻하므로 \\(a^{-3}=\\frac{1}{a^3}\\)입니다.",
    },
    {
        "code": "d1_exp_log_03",
        "day": 1,
        "subject": "math1",
        "chapter": "지수와 로그",
        "concept_code": "d1_math1_1_17_로그의_곱셈_성질",
        "type": "multiple_choice",
        "prompt": "\\(M>0,\\ N>0\\)일 때 옳은 것은?",
        "choices": [
            "\\(\\log_a(M+N)=\\log_aM+\\log_aN\\)",
            "\\(\\log_a(MN)=\\log_aM+\\log_aN\\)",
            "\\(\\log_a\\frac{M}{N}=\\log_aM+\\log_aN\\)",
            "\\(\\log_a(MN)=\\log_aM\\log_aN\\)",
        ],
        "answer_index": 1,
        "explanation": "로그에서 곱은 로그의 합으로 바뀝니다.",
    },
    {
        "code": "d1_exp_log_04",
        "day": 1,
        "subject": "math1",
        "chapter": "지수와 로그",
        "concept_code": "d1_math1_1_20_밑의_변환_공식",
        "type": "multiple_choice",
        "prompt": "로그의 밑의 변환 공식으로 옳은 것은?",
        "choices": [
            "\\(\\log_a b=\\frac{\\log_c a}{\\log_c b}\\)",
            "\\(\\log_a b=\\frac{\\log_c b}{\\log_c a}\\)",
            "\\(\\log_a b=\\log_c a+\\log_c b\\)",
            "\\(\\log_a b=\\log_c(ab)\\)",
        ],
        "answer_index": 1,
        "explanation": "\\(\\log_a b=\\frac{\\log_c b}{\\log_c a}\\)입니다.",
    },
    {
        "code": "d1_exp_log_05",
        "day": 1,
        "subject": "math1",
        "chapter": "지수와 로그",
        "concept_code": "d1_math1_1_13_로그가_정의되기_위한_밑_조건",
        "type": "multiple_choice",
        "prompt": "\\(\\log_{x-1}(3-x)\\)가 정의되기 위한 조건으로 옳은 것은?",
        "choices": ["\\(x>1\\)", "\\(1<x<3\\)", "\\(1<x<3,\\ x\\neq2\\)", "\\(x<3\\)"],
        "answer_index": 2,
        "explanation": "밑은 양수이고 1이 아니어야 하므로 \\(x>1,\\ x\\neq2\\), 진수는 양수이므로 \\(x<3\\)입니다.",
    },
    {
        "code": "d1_exp_func_01",
        "day": 1,
        "subject": "math1",
        "chapter": "지수함수와 로그함수",
        "concept_code": "d1_math1_2_3_0_a_1일_때_지수함수_감소",
        "type": "multiple_choice",
        "prompt": "\\(0<a<1\\)이고 \\(a^x>a^y\\)일 때 반드시 옳은 것은?",
        "choices": ["\\(x>y\\)", "\\(x<y\\)", "\\(x=y\\)", "판단할 수 없다"],
        "answer_index": 1,
        "explanation": "\\(0<a<1\\)인 지수함수는 감소함수이므로 지수의 대소관계가 반대가 됩니다.",
    },
    {
        "code": "d1_exp_func_02",
        "day": 1,
        "subject": "math1",
        "chapter": "지수함수와 로그함수",
        "concept_code": "d1_math1_2_15_로그방정식에서_진수조건_확인",
        "type": "multiple_choice",
        "prompt": "\\(\\log_2(x-3)\\)이 포함된 식을 다룰 때 먼저 확인해야 하는 조건은?",
        "choices": ["\\(x\\ge3\\)", "\\(x>3\\)", "\\(x\\neq3\\)", "\\(x>0\\)"],
        "answer_index": 1,
        "explanation": "로그의 진수는 반드시 양수이므로 \\(x-3>0\\), 즉 \\(x>3\\)입니다.",
    },
    {
        "code": "d1_exp_func_03",
        "day": 1,
        "subject": "math1",
        "chapter": "지수함수와 로그함수",
        "concept_code": "d1_math1_2_10_지수함수와_로그함수의_역함수_관계",
        "type": "true_false",
        "prompt": "지수함수 \\(y=a^x\\)와 로그함수 \\(y=\\log_a x\\)는 서로 역함수이므로 두 그래프는 직선 \\(y=x\\)에 대하여 대칭이다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "서로 역함수인 두 함수의 그래프는 \\(y=x\\)에 대하여 대칭입니다.",
    },
    {
        "code": "d1_exp_func_04",
        "day": 1,
        "subject": "math1",
        "chapter": "지수함수와 로그함수",
        "concept_code": "d1_math1_2_19_지수_로그함수_그래프의_평행이동",
        "type": "multiple_choice",
        "prompt": "함수 \\(y=\\log_2(x-4)+1\\)의 수직점근선은?",
        "choices": ["\\(x=1\\)", "\\(x=2\\)", "\\(x=4\\)", "\\(y=4\\)"],
        "answer_index": 2,
        "explanation": "\\(y=\\log_2x\\)의 점근선 \\(x=0\\)이 오른쪽으로 4만큼 이동하므로 \\(x=4\\)입니다.",
    },
    {
        "code": "d1_trig_01",
        "day": 1,
        "subject": "math1",
        "chapter": "삼각함수",
        "concept_code": "d1_math1_3_4_호도법",
        "type": "multiple_choice",
        "prompt": "\\(150^\\circ\\)를 호도법으로 나타낸 것은?",
        "choices": ["\\(\\frac{3\\pi}{5}\\)", "\\(\\frac{5\\pi}{6}\\)", "\\(\\frac{6\\pi}{5}\\)", "\\(\\frac{5\\pi}{3}\\)"],
        "answer_index": 1,
        "explanation": "\\(150^\\circ\\times\\frac{\\pi}{180^\\circ}=\\frac{5\\pi}{6}\\)입니다.",
    },
    {
        "code": "d1_trig_02",
        "day": 1,
        "subject": "math1",
        "chapter": "삼각함수",
        "concept_code": "d1_math1_3_12_sin_2_theta_cos_2_theta_1",
        "type": "multiple_choice",
        "prompt": "\\(\\sin\\theta=\\frac{3}{5}\\)이고 \\(\\theta\\)가 제2사분면의 각일 때 \\(\\cos\\theta\\)는?",
        "choices": ["\\(\\frac45\\)", "\\(-\\frac45\\)", "\\(\\frac35\\)", "\\(-\\frac35\\)"],
        "answer_index": 1,
        "explanation": "\\(\\sin^2\\theta+\\cos^2\\theta=1\\)이고 제2사분면에서는 cos이 음수입니다.",
    },
    {
        "code": "d1_trig_03",
        "day": 1,
        "subject": "math1",
        "chapter": "삼각함수",
        "concept_code": "d1_math1_3_13_사분면에_따른_sin_부호",
        "type": "multiple_choice",
        "prompt": "\\(\\sin\\theta<0\\), \\(\\cos\\theta<0\\)이면 \\(\\theta\\)의 동경은 어느 사분면에 있는가?",
        "choices": ["제1사분면", "제2사분면", "제3사분면", "제4사분면"],
        "answer_index": 2,
        "explanation": "sin과 cos이 모두 음수인 곳은 제3사분면입니다.",
    },
    {
        "code": "d1_trig_04",
        "day": 1,
        "subject": "math1",
        "chapter": "삼각함수",
        "concept_code": "d1_math1_3_27_y_sin_bx_cos_bx에서_주기_변화",
        "type": "multiple_choice",
        "prompt": "함수 \\(y=\\sin 3x\\)의 주기는?",
        "choices": ["\\(\\frac{\\pi}{3}\\)", "\\(\\frac{2\\pi}{3}\\)", "\\(\\pi\\)", "\\(2\\pi\\)"],
        "answer_index": 1,
        "explanation": "\\(y=\\sin bx\\)의 주기는 \\(\\frac{2\\pi}{|b|}\\)이므로 \\(\\frac{2\\pi}{3}\\)입니다.",
    },
    {
        "code": "d1_limit_01",
        "day": 1,
        "subject": "math2",
        "chapter": "함수의 극한",
        "concept_code": "d1_math2_4_4_극한_존재_조건_좌극한과_우극한의_일치",
        "type": "multiple_choice",
        "prompt": "\\(\\lim_{x\\to a}f(x)\\)가 존재하기 위한 조건으로 옳은 것은?",
        "choices": ["\\(f(a)=0\\)", "좌극한과 우극한이 같다", "\\(f(a)\\)가 반드시 존재한다", "함수가 미분가능하다"],
        "answer_index": 1,
        "explanation": "한 점에서 극한이 존재하려면 좌극한과 우극한이 존재하고 서로 같아야 합니다.",
    },
    {
        "code": "d1_limit_02",
        "day": 1,
        "subject": "math2",
        "chapter": "함수의 극한",
        "concept_code": "d1_math2_4_11_0_0_유리식의_인수분해_약분",
        "type": "multiple_choice",
        "prompt": "\\(\\lim_{x\\to2}\\frac{x^2-4}{x-2}\\)를 계산할 때 가장 먼저 할 일은?",
        "choices": ["\\(x=2\\)를 그대로 대입한다", "분자를 인수분해한다", "분모를 유리화한다", "최고차항으로 나눈다"],
        "answer_index": 1,
        "explanation": "\\(0/0\\) 꼴의 유리식이므로 \\(x^2-4=(x-2)(x+2)\\)로 인수분해해 약분합니다.",
    },
    {
        "code": "d1_limit_03",
        "day": 1,
        "subject": "math2",
        "chapter": "함수의 극한",
        "concept_code": "d1_math2_4_14_최고차항으로_나누는_방법",
        "type": "multiple_choice",
        "prompt": "\\(\\lim_{x\\to\\infty}\\frac{2x^2+1}{x^2-3x}\\)의 값을 빠르게 판단할 때 비교해야 하는 것은?",
        "choices": ["상수항", "일차항의 계수", "최고차항의 계수", "모든 계수의 합"],
        "answer_index": 2,
        "explanation": "분자와 분모의 차수가 같으므로 최고차항의 계수 비를 확인합니다.",
    },
    {
        "code": "d1_limit_04",
        "day": 1,
        "subject": "math2",
        "chapter": "함수의 극한",
        "concept_code": "d1_math2_4_5_함숫값과_극한값은_다를_수_있음",
        "type": "true_false",
        "prompt": "\\(\\lim_{x\\to a}f(x)\\)가 존재하면 반드시 \\(f(a)=\\lim_{x\\to a}f(x)\\)이다.",
        "choices": ["O", "X"],
        "answer_index": 1,
        "explanation": "극한값과 함수값은 서로 다를 수 있습니다. 두 값이 같은 것은 연속일 때입니다.",
    },
    {
        "code": "d1_continuity_01",
        "day": 1,
        "subject": "math2",
        "chapter": "함수의 연속",
        "concept_code": "d1_math2_5_2_lim_f_x_f_a",
        "type": "multiple_choice",
        "prompt": "함수 \\(f(x)\\)가 \\(x=a\\)에서 연속이기 위한 관계는?",
        "choices": ["\\(f(a)=0\\)", "\\(\\lim_{x\\to a}f(x)=0\\)", "\\(\\lim_{x\\to a}f(x)=f(a)\\)", "\\(f'(a)=0\\)"],
        "answer_index": 2,
        "explanation": "극한값이 존재하고 그 값이 함수값과 같아야 연속입니다.",
    },
    {
        "code": "d1_continuity_02",
        "day": 1,
        "subject": "math2",
        "chapter": "함수의 연속",
        "concept_code": "d1_math2_5_1_x_a에서_연속의_정의",
        "type": "multiple_choice",
        "prompt": "함수 \\(f(x)=\\begin{cases}x+1 &(x<1)\\\\ a &(x=1)\\\\ 3-x &(x>1)\\end{cases}\\)가 \\(x=1\\)에서 연속일 때 \\(a\\)는?",
        "choices": ["\\(0\\)", "\\(1\\)", "\\(2\\)", "\\(3\\)"],
        "answer_index": 2,
        "explanation": "좌극한과 우극한이 모두 2이므로 함수값도 \\(a=2\\)여야 합니다.",
    },
    {
        "code": "d1_continuity_03",
        "day": 1,
        "subject": "math2",
        "chapter": "함수의 연속",
        "concept_code": "d1_math2_5_9_닫힌구간_연속과_최대_최소_정리",
        "type": "true_false",
        "prompt": "함수가 닫힌구간 \\([a,b]\\)에서 연속이면 그 구간에서 반드시 최댓값과 최솟값을 갖는다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "닫힌구간에서 연속인 함수에 대한 최대·최소 정리입니다.",
    },
    {
        "code": "d1_continuity_04",
        "day": 1,
        "subject": "math2",
        "chapter": "함수의 연속",
        "concept_code": "d1_math2_5_10_사잇값정리",
        "type": "multiple_choice",
        "prompt": "함수 \\(f(x)\\)가 \\([1,3]\\)에서 연속이고 \\(f(1)<0<f(3)\\)일 때 반드시 말할 수 있는 것은?",
        "choices": [
            "\\(f(x)=0\\)의 해가 없다",
            "\\((1,3)\\)에서 \\(f(c)=0\\)인 \\(c\\)가 적어도 하나 존재한다",
            "\\(f(x)=0\\)의 해가 정확히 하나 존재한다",
            "\\(f(x)\\)는 증가함수이다",
        ],
        "answer_index": 1,
        "explanation": "사잇값정리에 의해 0을 함수값으로 갖는 점이 적어도 하나 존재합니다. 정확히 하나라고 할 수는 없습니다.",
    },
    {
        "code": "d1_perm_01",
        "day": 1,
        "subject": "probability",
        "chapter": "여러 가지 순열",
        "concept_code": "d1_probability_6_3_순열의_뜻",
        "type": "multiple_choice",
        "prompt": "서로 다른 \\(n\\)개 중에서 \\(r\\)개를 뽑아 순서를 고려하여 나열하는 경우의 수는?",
        "choices": ["\\({}_nC_r\\)", "\\({}_nP_r\\)", "\\(n^r\\)", "\\({}_nH_r\\)"],
        "answer_index": 1,
        "explanation": "선택한 뒤 순서까지 고려하는 경우는 순열 \\({}_nP_r\\)입니다.",
    },
    {
        "code": "d1_perm_02",
        "day": 1,
        "subject": "probability",
        "chapter": "여러 가지 순열",
        "concept_code": "d1_probability_6_7_중복순열_n_r",
        "type": "multiple_choice",
        "prompt": "서로 다른 4개의 문자에서 중복을 허용하여 3개를 뽑아 일렬로 나열하는 경우의 수는?",
        "choices": ["\\(12\\)", "\\(24\\)", "\\(64\\)", "\\(81\\)"],
        "answer_index": 2,
        "explanation": "각 자리마다 4개 중 하나를 선택하므로 \\(4^3=64\\)입니다.",
    },
    {
        "code": "d1_perm_03",
        "day": 1,
        "subject": "probability",
        "chapter": "여러 가지 순열",
        "concept_code": "d1_probability_6_11_원순열_n_1",
        "type": "multiple_choice",
        "prompt": "서로 다른 \\(n\\)명을 원탁에 앉히는 원순열의 수는?",
        "choices": ["\\(n!\\)", "\\((n-1)!\\)", "\\(\\frac{n!}{2}\\)", "\\(n^n\\)"],
        "answer_index": 1,
        "explanation": "회전에 의해 같은 배열을 하나로 보므로 원순열은 \\((n-1)!\\)입니다.",
    },
    {
        "code": "d1_perm_04",
        "day": 1,
        "subject": "probability",
        "chapter": "여러 가지 순열",
        "concept_code": "d1_probability_6_13_같은_것이_있는_순열_공식",
        "type": "multiple_choice",
        "prompt": "문자 \\(A,A,B,B,C\\)를 모두 일렬로 나열하는 서로 다른 방법의 수를 구할 때 사용하는 식은?",
        "choices": ["\\(5!\\)", "\\(\\frac{5!}{2!}\\)", "\\(\\frac{5!}{2!2!}\\)", "\\(\\frac{5!}{3!}\\)"],
        "answer_index": 2,
        "explanation": "A가 2개, B가 2개이므로 같은 것이 있는 순열 \\(\\frac{5!}{2!2!}\\)을 사용합니다.",
    },
    {
        "code": "d1_comb_01",
        "day": 1,
        "subject": "probability",
        "chapter": "중복조합과 이항정리",
        "concept_code": "d1_probability_7_3_nhr_n_r_1cr",
        "type": "multiple_choice",
        "prompt": "\\({}_nH_r\\)과 같은 것은?",
        "choices": ["\\({}_nC_r\\)", "\\({}_{n+r}C_r\\)", "\\({}_{n+r-1}C_r\\)", "\\({}_{n-1}C_r\\)"],
        "answer_index": 2,
        "explanation": "중복조합의 공식은 \\({}_nH_r={}_{n+r-1}C_r\\)입니다.",
    },
    {
        "code": "d1_comb_02",
        "day": 1,
        "subject": "probability",
        "chapter": "중복조합과 이항정리",
        "concept_code": "d1_probability_7_4_음이_아닌_정수해와_중복조합_관계",
        "type": "multiple_choice",
        "prompt": "음이 아닌 정수 \\(x,y,z\\)에 대하여 \\(x+y+z=5\\)의 해의 개수를 나타내는 식은?",
        "choices": ["\\({}_3C_5\\)", "\\({}_3H_5\\)", "\\({}_5P_3\\)", "\\(3^5\\)"],
        "answer_index": 1,
        "explanation": "3종류에서 중복을 허용하여 5개를 선택하는 것과 같으므로 \\({}_3H_5\\)입니다.",
    },
    {
        "code": "d1_comb_03",
        "day": 1,
        "subject": "probability",
        "chapter": "중복조합과 이항정리",
        "concept_code": "d1_probability_7_8_이항정리_일반항",
        "type": "multiple_choice",
        "prompt": "\\((a+b)^n\\)의 전개식에서 \\(a^{n-r}b^r\\)의 계수는?",
        "choices": ["\\({}_nP_r\\)", "\\({}_nC_r\\)", "\\({}_nH_r\\)", "\\(n^r\\)"],
        "answer_index": 1,
        "explanation": "이항정리의 일반항은 \\({}_nC_r a^{n-r}b^r\\)입니다.",
    },
    {
        "code": "d1_comb_04",
        "day": 1,
        "subject": "probability",
        "chapter": "중복조합과 이항정리",
        "concept_code": "d1_probability_7_9_특정_항의_계수_찾기",
        "type": "multiple_choice",
        "prompt": "\\((1+2x)^4\\)의 전개식에서 \\(x^2\\)의 계수는?",
        "choices": ["\\(12\\)", "\\(16\\)", "\\(24\\)", "\\(32\\)"],
        "answer_index": 2,
        "explanation": "\\({}_4C_2(2x)^2=6\\times4x^2=24x^2\\)입니다.",
    },
    {
        "code": "d1_comb_05",
        "day": 1,
        "subject": "probability",
        "chapter": "중복조합과 이항정리",
        "concept_code": "d1_probability_7_12_짝수항과_홀수항_이항계수_합",
        "type": "multiple_choice",
        "prompt": "\\({}_8C_0+{}_8C_2+{}_8C_4+{}_8C_6+{}_8C_8\\)의 값은?",
        "choices": ["\\(64\\)", "\\(128\\)", "\\(256\\)", "\\(512\\)"],
        "answer_index": 1,
        "explanation": "\\(n\\ge1\\)일 때 짝수 번째 이항계수의 합은 \\(2^{n-1}\\)이므로 \\(2^7=128\\)입니다.",
    },
]


DAY2_FORMULA_QUIZ_ITEMS = [
    {
        "code": "d2_sine_cosine_01",
        "day": 2,
        "subject": "math1",
        "chapter": "사인법칙과 코사인법칙",
        "concept_code": "d2_math1_1_2_a_sina_b_sinb_c_sinc_2r",
        "type": "multiple_choice",
        "prompt": "삼각형 \\(ABC\\)의 외접원의 반지름을 \\(R\\)이라 할 때 옳은 것은?",
        "choices": ["\\(\\frac{a}{\\sin A}=R\\)", "\\(\\frac{a}{\\sin A}=2R\\)", "\\(a\\sin A=2R\\)", "\\(\\frac{\\sin A}{a}=2R\\)"],
        "answer_index": 1,
        "explanation": "사인법칙은 \\(\\frac{a}{\\sin A}=\\frac{b}{\\sin B}=\\frac{c}{\\sin C}=2R\\)입니다.",
    },
    {
        "code": "d2_sine_cosine_02",
        "day": 2,
        "subject": "math1",
        "chapter": "사인법칙과 코사인법칙",
        "concept_code": "d2_math1_1_6_세_변으로_각_구하기",
        "type": "multiple_choice",
        "prompt": "삼각형에서 세 변의 길이가 모두 주어지고 한 각의 크기를 구해야 할 때 가장 먼저 떠올릴 것은?",
        "choices": ["사인법칙", "코사인법칙", "호의 길이 공식", "등차수열의 합"],
        "answer_index": 1,
        "explanation": "세 변이 모두 주어진 경우 각을 구하려면 코사인법칙을 이용하는 것이 기본입니다.",
    },
    {
        "code": "d2_sine_cosine_03",
        "day": 2,
        "subject": "math1",
        "chapter": "사인법칙과 코사인법칙",
        "concept_code": "d2_math1_1_8_삼각형_넓이_1_2bc_sina",
        "type": "multiple_choice",
        "prompt": "두 변의 길이가 \\(a,b\\)이고 그 끼인각이 \\(C\\)일 때 삼각형의 넓이는?",
        "choices": ["\\(ab\\sin C\\)", "\\(\\frac12ab\\sin C\\)", "\\(\\frac12ab\\cos C\\)", "\\(ab\\cos C\\)"],
        "answer_index": 1,
        "explanation": "두 변과 끼인각을 알 때 넓이는 \\(S=\\frac12ab\\sin C\\)입니다.",
    },
    {
        "code": "d2_sine_cosine_04",
        "day": 2,
        "subject": "math1",
        "chapter": "사인법칙과 코사인법칙",
        "concept_code": "d2_math1_1_7_두_변과_끼인각으로_나머지_변_구하기",
        "type": "multiple_choice",
        "prompt": "삼각형 \\(ABC\\)에서 \\(a=5, b=7, C=60^\\circ\\)일 때 \\(c^2\\)을 구하는 데 사용하는 식은?",
        "choices": [
            "\\(c^2=5^2+7^2-2\\cdot5\\cdot7\\cos60^\\circ\\)",
            "\\(c^2=5^2+7^2+2\\cdot5\\cdot7\\cos60^\\circ\\)",
            "\\(c=5\\sin60^\\circ+7\\cos60^\\circ\\)",
            "\\(c^2=5\\cdot7\\sin60^\\circ\\)",
        ],
        "answer_index": 0,
        "explanation": "두 변과 끼인각이 주어졌으므로 코사인법칙 \\(c^2=a^2+b^2-2ab\\cos C\\)를 사용합니다.",
    },
    {
        "code": "d2_sine_cosine_05",
        "day": 2,
        "subject": "math1",
        "chapter": "사인법칙과 코사인법칙",
        "concept_code": "d2_math1_1_9_변_각_조건을_보고_사인법칙_vs_코사인법칙_선택",
        "type": "true_false",
        "prompt": "한 변의 길이와 그 대각, 그리고 다른 한 각이 주어진 삼각형에서는 사인법칙을 우선 고려할 수 있다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "변과 그 대각의 대응 관계가 주어지면 사인법칙을 활용하기 좋습니다.",
    },
    {
        "code": "d2_derivative_basic_01",
        "day": 2,
        "subject": "math2",
        "chapter": "미분계수와 도함수",
        "concept_code": "d2_math2_2_2_미분계수_정의",
        "type": "multiple_choice",
        "prompt": "\\(f'(a)\\)의 정의로 옳은 것은?",
        "choices": [
            "\\(\\lim_{h\\to0}\\frac{f(a+h)-f(a)}{h}\\)",
            "\\(\\lim_{h\\to0}\\frac{f(a+h)+f(a)}{h}\\)",
            "\\(\\lim_{x\\to a}\\frac{f(x)}{x}\\)",
            "\\(\\frac{f(a)}{a}\\)",
        ],
        "answer_index": 0,
        "explanation": "미분계수는 \\(f'(a)=\\lim_{h\\to0}\\frac{f(a+h)-f(a)}{h}\\)입니다.",
    },
    {
        "code": "d2_derivative_basic_02",
        "day": 2,
        "subject": "math2",
        "chapter": "미분계수와 도함수",
        "concept_code": "d2_math2_2_5_미분가능이면_연속",
        "type": "true_false",
        "prompt": "함수가 \\(x=a\\)에서 미분가능하면 \\(x=a\\)에서 연속이다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "미분가능하면 반드시 연속입니다.",
    },
    {
        "code": "d2_derivative_basic_03",
        "day": 2,
        "subject": "math2",
        "chapter": "미분계수와 도함수",
        "concept_code": "d2_math2_2_6_연속이어도_미분가능은_아님",
        "type": "true_false",
        "prompt": "함수가 \\(x=a\\)에서 연속이면 반드시 \\(x=a\\)에서 미분가능하다.",
        "choices": ["O", "X"],
        "answer_index": 1,
        "explanation": "연속이더라도 뾰족점 등에서는 미분가능하지 않을 수 있습니다.",
    },
    {
        "code": "d2_derivative_basic_04",
        "day": 2,
        "subject": "math2",
        "chapter": "미분계수와 도함수",
        "concept_code": "d2_math2_2_10_x_n_미분",
        "type": "multiple_choice",
        "prompt": "\\(f(x)=x^4\\)일 때 \\(f'(x)\\)는?",
        "choices": ["\\(x^3\\)", "\\(3x^3\\)", "\\(4x^3\\)", "\\(4x^4\\)"],
        "answer_index": 2,
        "explanation": "\\((x^n)'=nx^{n-1}\\)이므로 \\((x^4)'=4x^3\\)입니다.",
    },
    {
        "code": "d2_derivative_basic_05",
        "day": 2,
        "subject": "math2",
        "chapter": "미분계수와 도함수",
        "concept_code": "d2_math2_2_13_곱의_미분",
        "type": "multiple_choice",
        "prompt": "두 함수 \\(f,g\\)의 곱을 미분한 식으로 옳은 것은?",
        "choices": ["\\((fg)'=f'g'\\)", "\\((fg)'=f'g+fg'\\)", "\\((fg)'=f'+g'\\)", "\\((fg)'=fg'+g\\)"],
        "answer_index": 1,
        "explanation": "곱의 미분법은 \\((fg)'=f'g+fg'\\)입니다.",
    },
    {
        "code": "d2_derivative_basic_06",
        "day": 2,
        "subject": "math2",
        "chapter": "미분계수와 도함수",
        "concept_code": "d2_math2_2_7_접선_기울기_의미",
        "type": "multiple_choice",
        "prompt": "미분계수 \\(f'(a)\\)가 그래프에서 의미하는 것은?",
        "choices": ["\\(x=a\\)에서 함수값", "\\(x=a\\)에서 접선의 기울기", "\\(x=a\\)에서 y절편", "\\(x=a\\)에서 넓이"],
        "answer_index": 1,
        "explanation": "미분계수는 해당 점에서 접선의 기울기를 뜻합니다.",
    },
    {
        "code": "d2_derivative_use1_01",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑴",
        "concept_code": "d2_math2_3_1_접선_방정식",
        "type": "multiple_choice",
        "prompt": "곡선 \\(y=f(x)\\) 위의 점 \\((a,f(a))\\)에서 접선의 방정식으로 옳은 것은?",
        "choices": ["\\(y=f'(a)x\\)", "\\(y-f(a)=f'(a)(x-a)\\)", "\\(y-a=f(a)(x-f'(a))\\)", "\\(y=f(a)(x-a)\\)"],
        "answer_index": 1,
        "explanation": "접선의 기울기는 \\(f'(a)\\)이고 점 \\((a,f(a))\\)를 지나므로 점기울기식을 사용합니다.",
    },
    {
        "code": "d2_derivative_use1_02",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑴",
        "concept_code": "d2_math2_3_6_f_0이면_증가",
        "type": "multiple_choice",
        "prompt": "함수 \\(f(x)\\)가 어떤 구간에서 항상 \\(f'(x)>0\\)이면 그 구간에서 \\(f(x)\\)는?",
        "choices": ["증가한다", "감소한다", "항상 양수이다", "항상 0이다"],
        "answer_index": 0,
        "explanation": "도함수가 양수인 구간에서는 함수가 증가합니다.",
    },
    {
        "code": "d2_derivative_use1_03",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑴",
        "concept_code": "d2_math2_3_7_f_0이면_감소",
        "type": "multiple_choice",
        "prompt": "함수 \\(f(x)\\)가 어떤 구간에서 항상 \\(f'(x)<0\\)이면 그 구간에서 \\(f(x)\\)는?",
        "choices": ["증가한다", "감소한다", "항상 음수이다", "극댓값을 갖는다"],
        "answer_index": 1,
        "explanation": "도함수가 음수인 구간에서는 함수가 감소합니다.",
    },
    {
        "code": "d2_derivative_use1_04",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑴",
        "concept_code": "d2_math2_3_4_평균값정리_조건",
        "type": "multiple_choice",
        "prompt": "평균값정리를 적용하기 위해 기본적으로 필요한 조건은?",
        "choices": [
            "닫힌구간에서 미분가능하기만 하면 된다",
            "닫힌구간에서 연속이고 열린구간에서 미분가능해야 한다",
            "열린구간에서 연속이기만 하면 된다",
            "도함수가 항상 0이어야 한다",
        ],
        "answer_index": 1,
        "explanation": "평균값정리는 닫힌구간에서 연속이고 그 내부 열린구간에서 미분가능해야 합니다.",
    },
    {
        "code": "d2_derivative_use2_01",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑵",
        "concept_code": "d2_math2_4_2_극값의_필요조건_f_0",
        "type": "true_false",
        "prompt": "미분가능한 함수가 \\(x=a\\)에서 극값을 가지면 \\(f'(a)=0\\)이다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "미분가능한 함수가 내부점에서 극값을 가지면 미분계수는 0입니다.",
    },
    {
        "code": "d2_derivative_use2_02",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑵",
        "concept_code": "d2_math2_4_3_f_0은_극값의_충분조건이_아님",
        "type": "true_false",
        "prompt": "\\(f'(a)=0\\)이면 함수 \\(f(x)\\)는 반드시 \\(x=a\\)에서 극값을 갖는다.",
        "choices": ["O", "X"],
        "answer_index": 1,
        "explanation": "\\(f'(a)=0\\)은 극값의 필요조건일 수 있지만 충분조건은 아닙니다.",
    },
    {
        "code": "d2_derivative_use2_03",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑵",
        "concept_code": "d2_math2_4_4_에서_로_바뀌면_극대",
        "type": "multiple_choice",
        "prompt": "도함수의 부호가 \\(x=a\\)를 기준으로 \\(+\\rightarrow-\\)로 바뀐다면 \\(f(x)\\)는 \\(x=a\\)에서?",
        "choices": ["극대", "극소", "항상 0", "판단할 수 없다"],
        "answer_index": 0,
        "explanation": "증가하다가 감소하므로 \\(x=a\\)에서 극대입니다.",
    },
    {
        "code": "d2_derivative_use2_04",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑵",
        "concept_code": "d2_math2_4_5_에서_로_바뀌면_극소",
        "type": "multiple_choice",
        "prompt": "도함수의 부호가 \\(x=a\\)를 기준으로 \\(-\\rightarrow+\\)로 바뀐다면 \\(f(x)\\)는 \\(x=a\\)에서?",
        "choices": ["극대", "극소", "항상 양수", "판단할 수 없다"],
        "answer_index": 1,
        "explanation": "감소하다가 증가하므로 \\(x=a\\)에서 극소입니다.",
    },
    {
        "code": "d2_derivative_use2_05",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑵",
        "concept_code": "d2_math2_4_7_닫힌구간_최대_최소에서_끝점_확인",
        "type": "multiple_choice",
        "prompt": "닫힌구간에서 함수의 최댓값과 최솟값을 구할 때 반드시 함께 확인해야 하는 것은?",
        "choices": ["극값을 갖는 점만 확인한다", "도함수가 1인 점만 확인한다", "극값 후보와 양 끝점을 함께 확인한다", "함수값이 0인 점만 확인한다"],
        "answer_index": 2,
        "explanation": "닫힌구간의 최댓값·최솟값은 내부의 극값 후보뿐 아니라 양 끝점의 함수값도 비교해야 합니다.",
    },
    {
        "code": "d2_derivative_use2_06",
        "day": 2,
        "subject": "math2",
        "chapter": "도함수의 활용 ⑵",
        "concept_code": "d2_math2_4_9_방정식_실근_수와_그래프_교점",
        "type": "multiple_choice",
        "prompt": "방정식 \\(f(x)=k\\)의 서로 다른 실근의 개수를 그래프로 판단할 때 확인해야 하는 것은?",
        "choices": ["\\(y=f(x)\\)와 \\(y=k\\)의 교점 개수", "\\(f'(x)=k\\)의 해의 개수", "x축과 y축의 교점 개수", "\\(f(x)\\)의 최고차항 계수"],
        "answer_index": 0,
        "explanation": "\\(f(x)=k\\)의 해는 그래프 \\(y=f(x)\\)와 수평선 \\(y=k\\)의 교점의 x좌표입니다.",
    },
    {
        "code": "d2_probability_01",
        "day": 2,
        "subject": "probability",
        "chapter": "확률의 뜻과 활용",
        "concept_code": "d2_probability_5_5_수학적_확률",
        "type": "multiple_choice",
        "prompt": "모든 근원사건이 일어날 가능성이 같을 때 사건 \\(A\\)의 확률은?",
        "choices": ["\\(P(A)=\\frac{n(S)}{n(A)}\\)", "\\(P(A)=\\frac{n(A)}{n(S)}\\)", "\\(P(A)=n(A)+n(S)\\)", "\\(P(A)=n(A)n(S)\\)"],
        "answer_index": 1,
        "explanation": "수학적 확률은 전체 경우의 수 중 사건 A에 해당하는 경우의 수의 비입니다.",
    },
    {
        "code": "d2_probability_02",
        "day": 2,
        "subject": "probability",
        "chapter": "확률의 뜻과 활용",
        "concept_code": "d2_probability_5_12_확률_덧셈정리",
        "type": "multiple_choice",
        "prompt": "두 사건 \\(A,B\\)에 대하여 옳은 확률의 덧셈정리는?",
        "choices": [
            "\\(P(A\\cup B)=P(A)+P(B)\\)",
            "\\(P(A\\cup B)=P(A)+P(B)-P(A\\cap B)\\)",
            "\\(P(A\\cup B)=P(A)P(B)\\)",
            "\\(P(A\\cup B)=P(A\\cap B)-P(A)-P(B)\\)",
        ],
        "answer_index": 1,
        "explanation": "교집합을 두 번 세었으므로 \\(P(A\\cap B)\\)를 한 번 빼야 합니다.",
    },
    {
        "code": "d2_probability_03",
        "day": 2,
        "subject": "probability",
        "chapter": "확률의 뜻과 활용",
        "concept_code": "d2_probability_5_14_적어도_하나와_여사건_활용",
        "type": "multiple_choice",
        "prompt": "사건 \\(A\\)가 적어도 한 번 일어날 확률을 구할 때 자주 사용하는 방법은?",
        "choices": ["반드시 경우를 모두 직접 센다", "A가 한 번도 일어나지 않을 확률을 1에서 뺀다", "확률을 모두 더한다", "조건부확률만 사용한다"],
        "answer_index": 1,
        "explanation": "적어도 한 번은 여사건인 '한 번도 일어나지 않음'을 이용하면 간단한 경우가 많습니다.",
    },
    {
        "code": "d2_probability_04",
        "day": 2,
        "subject": "probability",
        "chapter": "확률의 뜻과 활용",
        "concept_code": "d2_probability_5_11_배반사건",
        "type": "true_false",
        "prompt": "두 사건 \\(A,B\\)가 서로 배반이면 \\(P(A\\cap B)=0\\)이다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "서로 배반인 사건은 동시에 일어날 수 없으므로 교사건의 확률은 0입니다.",
    },
    {
        "code": "d2_conditional_01",
        "day": 2,
        "subject": "probability",
        "chapter": "조건부확률",
        "concept_code": "d2_probability_6_3_조건부확률_공식",
        "type": "multiple_choice",
        "prompt": "\\(P(A)>0\\)일 때 조건부확률 \\(P(B|A)\\)는?",
        "choices": ["\\(\\frac{P(A\\cap B)}{P(A)}\\)", "\\(\\frac{P(A)}{P(B)}\\)", "\\(P(A)+P(B)\\)", "\\(P(A)P(B)\\)"],
        "answer_index": 0,
        "explanation": "\\(P(B|A)=\\frac{P(A\\cap B)}{P(A)}\\)입니다.",
    },
    {
        "code": "d2_conditional_02",
        "day": 2,
        "subject": "probability",
        "chapter": "조건부확률",
        "concept_code": "d2_probability_6_4_곱셈정리",
        "type": "multiple_choice",
        "prompt": "확률의 곱셈정리로 옳은 것은?",
        "choices": [
            "\\(P(A\\cap B)=P(A)+P(B|A)\\)",
            "\\(P(A\\cap B)=P(A)P(B|A)\\)",
            "\\(P(A\\cap B)=P(A)-P(B|A)\\)",
            "\\(P(A\\cap B)=\\frac{P(A)}{P(B|A)}\\)",
        ],
        "answer_index": 1,
        "explanation": "조건부확률 식을 변형하면 \\(P(A\\cap B)=P(A)P(B|A)\\)입니다.",
    },
    {
        "code": "d2_conditional_03",
        "day": 2,
        "subject": "probability",
        "chapter": "조건부확률",
        "concept_code": "d2_probability_6_7_독립_조건",
        "type": "multiple_choice",
        "prompt": "두 사건 \\(A,B\\)가 서로 독립일 때 옳은 것은?",
        "choices": ["\\(P(A\\cap B)=0\\)", "\\(P(A\\cap B)=P(A)+P(B)\\)", "\\(P(A\\cap B)=P(A)P(B)\\)", "\\(P(A)=P(B)\\)"],
        "answer_index": 2,
        "explanation": "독립인 두 사건은 \\(P(A\\cap B)=P(A)P(B)\\)를 만족합니다.",
    },
    {
        "code": "d2_conditional_04",
        "day": 2,
        "subject": "probability",
        "chapter": "조건부확률",
        "concept_code": "d2_probability_6_8_독립과_배반_차이",
        "type": "true_false",
        "prompt": "두 사건이 서로 배반이면 두 사건은 항상 서로 독립이다.",
        "choices": ["O", "X"],
        "answer_index": 1,
        "explanation": "배반과 독립은 다른 개념입니다. 확률이 0이 아닌 두 배반사건은 일반적으로 독립이 아닙니다.",
    },
    {
        "code": "d2_conditional_05",
        "day": 2,
        "subject": "probability",
        "chapter": "조건부확률",
        "concept_code": "d2_probability_6_11_이항_독립시행_확률",
        "type": "multiple_choice",
        "prompt": "성공확률이 \\(p\\)인 독립시행을 \\(n\\)번 시행하여 정확히 \\(r\\)번 성공할 확률은?",
        "choices": ["\\({}_nC_r p^r(1-p)^{n-r}\\)", "\\({}_nP_r p^r(1-p)^{n-r}\\)", "\\(p^n\\)", "\\({}_nC_r p^{n-r}(1-p)^r\\)"],
        "answer_index": 0,
        "explanation": "성공할 r번의 위치를 고르는 경우의 수와 각 시행 확률을 곱하여 \\({}_nC_r p^r(1-p)^{n-r}\\)가 됩니다.",
    },
]


DAY3_FORMULA_QUIZ_ITEMS = [
    {
        "code": "d3_sequence_01",
        "day": 3,
        "subject": "math1",
        "chapter": "등차수열과 등비수열",
        "concept_code": "d3_math1_1_5_등차_일반항",
        "type": "multiple_choice",
        "prompt": "첫째항이 \\(a\\), 공차가 \\(d\\)인 등차수열의 일반항은?",
        "choices": ["\\(a_n=a+nd\\)", "\\(a_n=a+(n-1)d\\)", "\\(a_n=an+d\\)", "\\(a_n=a+(n+1)d\\)"],
        "answer_index": 1,
        "explanation": "등차수열의 일반항은 \\(a_n=a+(n-1)d\\)입니다.",
    },
    {
        "code": "d3_sequence_02",
        "day": 3,
        "subject": "math1",
        "chapter": "등차수열과 등비수열",
        "concept_code": "d3_math1_1_4_공차",
        "type": "multiple_choice",
        "prompt": "등차수열에서 \\(a_3=5\\), 공차가 \\(2\\)일 때 \\(a_4\\)는?",
        "choices": ["\\(3\\)", "\\(5\\)", "\\(7\\)", "\\(10\\)"],
        "answer_index": 2,
        "explanation": "등차수열의 이웃한 항은 공차만큼 차이나므로 \\(a_4=5+2=7\\)입니다.",
    },
    {
        "code": "d3_sequence_03",
        "day": 3,
        "subject": "math1",
        "chapter": "등차수열과 등비수열",
        "concept_code": "d3_math1_1_11_등비_일반항",
        "type": "multiple_choice",
        "prompt": "첫째항이 \\(a\\), 공비가 \\(r\\)인 등비수열의 일반항은?",
        "choices": ["\\(a_n=ar^n\\)", "\\(a_n=ar^{n-1}\\)", "\\(a_n=a+(n-1)r\\)", "\\(a_n=a+r^n\\)"],
        "answer_index": 1,
        "explanation": "등비수열의 일반항은 \\(a_n=ar^{n-1}\\)입니다.",
    },
    {
        "code": "d3_sequence_04",
        "day": 3,
        "subject": "math1",
        "chapter": "등차수열과 등비수열",
        "concept_code": "d3_math1_1_6_등차중항",
        "type": "multiple_choice",
        "prompt": "세 수 \\(a,b,c\\)가 이 순서로 등차수열을 이룰 때 옳은 관계는?",
        "choices": ["\\(b=a+c\\)", "\\(2b=a+c\\)", "\\(b^2=ac\\)", "\\(a^2=bc\\)"],
        "answer_index": 1,
        "explanation": "등차중항은 양옆 두 항의 산술평균이므로 \\(2b=a+c\\)입니다.",
    },
    {
        "code": "d3_sequence_05",
        "day": 3,
        "subject": "math1",
        "chapter": "등차수열과 등비수열",
        "concept_code": "d3_math1_1_12_등비중항",
        "type": "multiple_choice",
        "prompt": "세 양수 \\(a,b,c\\)가 이 순서로 등비수열을 이룰 때 옳은 관계는?",
        "choices": ["\\(2b=a+c\\)", "\\(b=a+c\\)", "\\(b^2=ac\\)", "\\(a^2=bc\\)"],
        "answer_index": 2,
        "explanation": "등비중항에서는 \\(b^2=ac\\)가 성립합니다.",
    },
    {
        "code": "d3_sequence_sum_01",
        "day": 3,
        "subject": "math1",
        "chapter": "수열의 합과 수학적 귀납법",
        "concept_code": "d3_math1_1_7_등차수열_합",
        "type": "multiple_choice",
        "prompt": "첫째항이 \\(a\\), 공차가 \\(d\\)인 등차수열의 첫째항부터 제\\(n\\)항까지의 합은?",
        "choices": [
            "\\(\\frac{n}{2}\\{2a+(n-1)d\\}\\)",
            "\\(n\\{2a+(n-1)d\\}\\)",
            "\\(\\frac{n}{2}\\{a+(n-1)d\\}\\)",
            "\\(a+(n-1)d\\)",
        ],
        "answer_index": 0,
        "explanation": "등차수열의 합은 \\(S_n=\\frac{n}{2}\\{2a+(n-1)d\\}\\)입니다.",
    },
    {
        "code": "d3_sequence_sum_02",
        "day": 3,
        "subject": "math1",
        "chapter": "수열의 합과 수학적 귀납법",
        "concept_code": "d3_math1_1_13_등비수열_합",
        "type": "multiple_choice",
        "prompt": "첫째항이 \\(a\\), 공비가 \\(r\\neq1\\)인 등비수열의 합으로 옳은 것은?",
        "choices": ["\\(S_n=\\frac{a(1-r^n)}{1-r}\\)", "\\(S_n=\\frac{a(1-r)}{1-r^n}\\)", "\\(S_n=a+(n-1)r\\)", "\\(S_n=ar^{n-1}\\)"],
        "answer_index": 0,
        "explanation": "등비수열의 합은 \\(r\\neq1\\)일 때 \\(S_n=\\frac{a(1-r^n)}{1-r}\\)로 나타낼 수 있습니다.",
    },
    {
        "code": "d3_sequence_sum_03",
        "day": 3,
        "subject": "math1",
        "chapter": "수열의 합과 수학적 귀납법",
        "concept_code": "d3_math1_1_14_r_1_예외",
        "type": "multiple_choice",
        "prompt": "등비수열의 공비가 \\(r=1\\)일 때 첫째항부터 제\\(n\\)항까지의 합은?",
        "choices": ["\\(a\\)", "\\(na\\)", "\\(a^n\\)", "\\(n+a\\)"],
        "answer_index": 1,
        "explanation": "공비가 1이면 모든 항이 a이므로 n개의 항의 합은 \\(na\\)입니다.",
    },
    {
        "code": "d3_sequence_sum_04",
        "day": 3,
        "subject": "math1",
        "chapter": "수열의 합과 수학적 귀납법",
        "concept_code": "d3_math1_2_10_sn과_an_관계",
        "type": "multiple_choice",
        "prompt": "\\(S_n\\)이 수열 \\(\\{a_n\\}\\)의 첫째항부터 제\\(n\\)항까지의 합일 때 \\(n\\ge2\\)에서 옳은 것은?",
        "choices": ["\\(a_n=S_n+S_{n-1}\\)", "\\(a_n=S_n-S_{n-1}\\)", "\\(a_n=S_{n-1}-S_n\\)", "\\(a_n=\\frac{S_n}{n}\\)"],
        "answer_index": 1,
        "explanation": "\\(S_n=a_1+\\cdots+a_n\\)이므로 \\(S_n-S_{n-1}=a_n\\)입니다.",
    },
    {
        "code": "d3_sequence_sum_05",
        "day": 3,
        "subject": "math1",
        "chapter": "수열의 합과 수학적 귀납법",
        "concept_code": "d3_math1_2_11_n_1_별도_처리",
        "type": "true_false",
        "prompt": "\\(S_n\\)이 첫째항부터 제\\(n\\)항까지의 합이면 \\(a_1=S_1\\)이다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "첫째항까지의 합은 첫째항 자체이므로 \\(a_1=S_1\\)입니다.",
    },
    {
        "code": "d3_sequence_sum_06",
        "day": 3,
        "subject": "math1",
        "chapter": "수열의 합과 수학적 귀납법",
        "concept_code": "d3_math1_2_5_sigma_k",
        "type": "multiple_choice",
        "prompt": "\\(\\sum_{k=1}^{n}k\\)와 같은 것은?",
        "choices": ["\\(\\frac{n(n-1)}{2}\\)", "\\(\\frac{n(n+1)}{2}\\)", "\\(n(n+1)\\)", "\\(n^2\\)"],
        "answer_index": 1,
        "explanation": "자연수의 합 공식은 \\(1+2+\\cdots+n=\\frac{n(n+1)}{2}\\)입니다.",
    },
    {
        "code": "d3_sequence_sum_07",
        "day": 3,
        "subject": "math1",
        "chapter": "수열의 합과 수학적 귀납법",
        "concept_code": "d3_math1_2_15_k_1_증명",
        "type": "multiple_choice",
        "prompt": "수학적 귀납법에서 \\(n=k\\)일 때 명제가 참이라고 가정한 뒤 다음으로 보이는 것은?",
        "choices": ["\\(n=1\\)일 때 거짓임을 보인다", "\\(n=k-1\\)일 때 참임을 보인다", "\\(n=k+1\\)일 때도 참임을 보인다", "모든 항을 직접 계산한다"],
        "answer_index": 2,
        "explanation": "귀납가정을 이용하여 다음 단계인 \\(n=k+1\\)에서도 명제가 성립함을 보입니다.",
    },
    {
        "code": "d3_integral_01",
        "day": 3,
        "subject": "math2",
        "chapter": "부정적분과 정적분",
        "concept_code": "d3_math2_3_4_x_n_적분",
        "type": "multiple_choice",
        "prompt": "\\(\\int x^2\\,dx\\)와 같은 것은?",
        "choices": ["\\(2x+C\\)", "\\(\\frac{x^3}{3}+C\\)", "\\(3x^2+C\\)", "\\(x^3+C\\)"],
        "answer_index": 1,
        "explanation": "\\(\\int x^n dx=\\frac{x^{n+1}}{n+1}+C\\)이므로 \\(\\int x^2dx=\\frac{x^3}{3}+C\\)입니다.",
    },
    {
        "code": "d3_integral_02",
        "day": 3,
        "subject": "math2",
        "chapter": "부정적분과 정적분",
        "concept_code": "d3_math2_3_3_적분상수",
        "type": "true_false",
        "prompt": "부정적분을 나타낼 때는 적분상수 \\(C\\)를 붙여야 한다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "같은 도함수를 갖는 함수들이 상수만큼 차이날 수 있으므로 적분상수 C를 붙입니다.",
    },
    {
        "code": "d3_integral_03",
        "day": 3,
        "subject": "math2",
        "chapter": "부정적분과 정적분",
        "concept_code": "d3_math2_3_7_정적분_정의와_기본_계산",
        "type": "multiple_choice",
        "prompt": "\\(F'(x)=f(x)\\)일 때 \\(\\int_a^b f(x)\\,dx\\)와 같은 것은?",
        "choices": ["\\(F(a)-F(b)\\)", "\\(F(b)-F(a)\\)", "\\(F(a)+F(b)\\)", "\\(F(a)F(b)\\)"],
        "answer_index": 1,
        "explanation": "정적분의 값은 원시함수에 대하여 \\(F(b)-F(a)\\)입니다.",
    },
    {
        "code": "d3_integral_04",
        "day": 3,
        "subject": "math2",
        "chapter": "부정적분과 정적분",
        "concept_code": "d3_math2_3_9_구간_뒤집기의_부호",
        "type": "multiple_choice",
        "prompt": "적분구간의 순서를 바꾼 식으로 옳은 것은?",
        "choices": [
            "\\(\\int_a^b f(x)dx=\\int_b^a f(x)dx\\)",
            "\\(\\int_a^b f(x)dx=-\\int_b^a f(x)dx\\)",
            "\\(\\int_a^b f(x)dx=0\\)",
            "\\(\\int_a^b f(x)dx=2\\int_b^a f(x)dx\\)",
        ],
        "answer_index": 1,
        "explanation": "정적분은 적분구간의 순서를 바꾸면 부호가 반대가 됩니다.",
    },
    {
        "code": "d3_integral_05",
        "day": 3,
        "subject": "math2",
        "chapter": "부정적분과 정적분",
        "concept_code": "d3_math2_3_12_기함수의_정적분",
        "type": "multiple_choice",
        "prompt": "\\(f(x)\\)가 기함수일 때 \\(\\int_{-a}^{a}f(x)\\,dx\\)의 값은?",
        "choices": ["\\(0\\)", "\\(\\int_0^a f(x)dx\\)", "\\(2\\int_0^a f(x)dx\\)", "\\(-2\\int_0^a f(x)dx\\)"],
        "answer_index": 0,
        "explanation": "기함수의 대칭구간 정적분은 0입니다.",
    },
    {
        "code": "d3_integral_application_01",
        "day": 3,
        "subject": "math2",
        "chapter": "정적분의 활용",
        "concept_code": "d3_math2_4_5_위_함수_아래_함수",
        "type": "multiple_choice",
        "prompt": "구간 전체에서 \\(f(x)\\ge g(x)\\)일 때 두 곡선 \\(y=f(x)\\), \\(y=g(x)\\) 사이의 넓이를 구하는 기본 형태는?",
        "choices": ["\\(\\int (g(x)-f(x))dx\\)", "\\(\\int (f(x)-g(x))dx\\)", "\\(\\int f(x)g(x)dx\\)", "\\(\\int (f(x)+g(x))dx\\)"],
        "answer_index": 1,
        "explanation": "두 곡선 사이 넓이는 기본적으로 위의 함수에서 아래의 함수를 뺀 뒤 적분합니다.",
    },
    {
        "code": "d3_integral_application_02",
        "day": 3,
        "subject": "math2",
        "chapter": "정적분의 활용",
        "concept_code": "d3_math2_4_2_x축_위아래_부호",
        "type": "true_false",
        "prompt": "함수가 x축 아래에 있는 구간에서는 정적분값이 음수가 될 수 있다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "정적분은 부호를 포함한 값이므로 함수가 x축 아래에 있으면 음수가 될 수 있습니다.",
    },
    {
        "code": "d3_integral_application_03",
        "day": 3,
        "subject": "math2",
        "chapter": "정적분의 활용",
        "concept_code": "d3_math2_4_8_속도_적분과_위치_변화량",
        "type": "multiple_choice",
        "prompt": "속도가 \\(v(t)\\)일 때 시각 \\(a\\)부터 \\(b\\)까지의 위치 변화량을 나타내는 것은?",
        "choices": ["\\(\\int_a^b v(t)dt\\)", "\\(\\int_a^b |v(t)|dt\\)", "\\(v(b)-v(a)\\)", "\\(\\int_a^b v'(t)dt\\)"],
        "answer_index": 0,
        "explanation": "속도를 시간에 대하여 적분하면 위치의 변화량을 얻습니다.",
    },
    {
        "code": "d3_integral_application_04",
        "day": 3,
        "subject": "math2",
        "chapter": "정적분의 활용",
        "concept_code": "d3_math2_4_9_속도_적분과_이동거리",
        "type": "multiple_choice",
        "prompt": "속도가 \\(v(t)\\)일 때 시각 \\(a\\)부터 \\(b\\)까지의 총 이동거리를 나타내는 것은?",
        "choices": ["\\(\\int_a^b v(t)dt\\)", "\\(\\int_a^b |v(t)|dt\\)", "\\(|v(b)-v(a)|\\)", "\\(v(a)+v(b)\\)"],
        "answer_index": 1,
        "explanation": "이동거리는 방향과 관계없이 이동한 양이므로 속도의 절댓값을 적분합니다.",
    },
    {
        "code": "d3_discrete_01",
        "day": 3,
        "subject": "probability",
        "chapter": "이산확률변수의 확률분포",
        "concept_code": "d3_probability_5_5_확률의_합_1",
        "type": "multiple_choice",
        "prompt": "이산확률변수 \\(X\\)의 확률질량함수에서 모든 가능한 값의 확률을 더한 값은?",
        "choices": ["\\(0\\)", "\\(1\\)", "\\(E(X)\\)", "\\(V(X)\\)"],
        "answer_index": 1,
        "explanation": "확률분포의 모든 확률의 합은 1입니다.",
    },
    {
        "code": "d3_discrete_02",
        "day": 3,
        "subject": "probability",
        "chapter": "이산확률변수의 확률분포",
        "concept_code": "d3_probability_5_11_e_ax_b",
        "type": "multiple_choice",
        "prompt": "확률변수 \\(X\\)에 대하여 \\(E(X)=3\\)일 때 \\(E(2X+1)\\)은?",
        "choices": ["\\(5\\)", "\\(6\\)", "\\(7\\)", "\\(8\\)"],
        "answer_index": 2,
        "explanation": "\\(E(aX+b)=aE(X)+b\\)이므로 \\(2\\times3+1=7\\)입니다.",
    },
    {
        "code": "d3_discrete_03",
        "day": 3,
        "subject": "probability",
        "chapter": "이산확률변수의 확률분포",
        "concept_code": "d3_probability_5_12_v_ax_b",
        "type": "multiple_choice",
        "prompt": "\\(V(X)=4\\)일 때 \\(V(3X+2)\\)는?",
        "choices": ["\\(12\\)", "\\(18\\)", "\\(36\\)", "\\(38\\)"],
        "answer_index": 2,
        "explanation": "\\(V(aX+b)=a^2V(X)\\)이므로 \\(3^2\\times4=36\\)입니다.",
    },
    {
        "code": "d3_discrete_04",
        "day": 3,
        "subject": "probability",
        "chapter": "이산확률변수의 확률분포",
        "concept_code": "d3_probability_5_16_평균_np",
        "type": "multiple_choice",
        "prompt": "\\(X\\sim B(n,p)\\)일 때 \\(E(X)\\)는?",
        "choices": ["\\(np\\)", "\\(np(1-p)\\)", "\\(\\sqrt{np(1-p)}\\)", "\\(\\frac{n}{p}\\)"],
        "answer_index": 0,
        "explanation": "이항분포 \\(B(n,p)\\)의 평균은 \\(np\\)입니다.",
    },
    {
        "code": "d3_continuous_01",
        "day": 3,
        "subject": "probability",
        "chapter": "연속확률변수의 확률분포",
        "concept_code": "d3_probability_6_6_한_점의_확률_0",
        "type": "true_false",
        "prompt": "연속확률변수 \\(X\\)에 대하여 한 점에서의 확률 \\(P(X=a)\\)는 0이다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "연속확률변수에서는 한 점에 해당하는 넓이가 0이므로 한 점의 확률도 0입니다.",
    },
    {
        "code": "d3_continuous_02",
        "day": 3,
        "subject": "probability",
        "chapter": "연속확률변수의 확률분포",
        "concept_code": "d3_probability_6_11_표준화_z_x_m_sigma",
        "type": "multiple_choice",
        "prompt": "확률변수 \\(X\\)의 평균이 \\(m\\), 표준편차가 \\(\\sigma\\)일 때 표준화한 확률변수 \\(Z\\)는?",
        "choices": ["\\(Z=\\frac{X-m}{\\sigma}\\)", "\\(Z=\\frac{X+m}{\\sigma}\\)", "\\(Z=\\frac{X}{m\\sigma}\\)", "\\(Z=X\\sigma-m\\)"],
        "answer_index": 0,
        "explanation": "표준화 공식은 \\(Z=\\frac{X-m}{\\sigma}\\)입니다.",
    },
    {
        "code": "d3_continuous_03",
        "day": 3,
        "subject": "probability",
        "chapter": "연속확률변수의 확률분포",
        "concept_code": "d3_probability_6_8_평균을_중심으로_대칭",
        "type": "true_false",
        "prompt": "정규분포의 그래프는 평균을 기준으로 좌우 대칭이다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "정규분포의 확률밀도함수 그래프는 평균을 중심으로 좌우 대칭입니다.",
    },
    {
        "code": "d3_estimation_01",
        "day": 3,
        "subject": "probability",
        "chapter": "통계적 추정",
        "concept_code": "d3_probability_7_8_e_xbar_m",
        "type": "multiple_choice",
        "prompt": "모평균이 \\(m\\)인 모집단에서 크기 \\(n\\)의 표본을 뽑을 때 표본평균 \\(\\overline{X}\\)의 평균은?",
        "choices": ["\\(0\\)", "\\(m\\)", "\\(\\frac{m}{n}\\)", "\\(nm\\)"],
        "answer_index": 1,
        "explanation": "표본평균의 평균은 모집단의 평균과 같은 \\(m\\)입니다.",
    },
    {
        "code": "d3_estimation_02",
        "day": 3,
        "subject": "probability",
        "chapter": "통계적 추정",
        "concept_code": "d3_probability_7_10_sigma_xbar_sigma_sqrt_n",
        "type": "multiple_choice",
        "prompt": "모표준편차가 \\(\\sigma\\)일 때 크기 \\(n\\)인 표본평균 \\(\\overline{X}\\)의 표준편차는?",
        "choices": ["\\(\\sigma\\)", "\\(\\frac{\\sigma}{n}\\)", "\\(\\frac{\\sigma}{\\sqrt n}\\)", "\\(\\frac{\\sigma^2}{n}\\)"],
        "answer_index": 2,
        "explanation": "표본평균의 표준편차는 \\(\\frac{\\sigma}{\\sqrt n}\\)입니다.",
    },
    {
        "code": "d3_estimation_03",
        "day": 3,
        "subject": "probability",
        "chapter": "통계적 추정",
        "concept_code": "d3_probability_7_17_표본_수가_커지면_구간_폭_감소",
        "type": "true_false",
        "prompt": "다른 조건이 같다면 표본의 크기 \\(n\\)이 커질수록 모평균의 신뢰구간은 일반적으로 좁아진다.",
        "choices": ["O", "X"],
        "answer_index": 0,
        "explanation": "표본 크기가 커지면 표준오차 \\(\\frac{\\sigma}{\\sqrt n}\\)가 작아지므로 신뢰구간의 폭도 좁아집니다.",
    },
]


SUTEUK_FORMULA_QUIZ_ITEMS = [
    *DAY1_FORMULA_QUIZ_ITEMS,
    *DAY2_FORMULA_QUIZ_ITEMS,
    *DAY3_FORMULA_QUIZ_ITEMS,
]


FORMULA_QUIZ_BY_DAY = {
    day: [item for item in SUTEUK_FORMULA_QUIZ_ITEMS if item["day"] == day]
    for day in range(1, 11)
}

FORMULA_QUIZ_BY_CODE = {item["code"]: item for item in SUTEUK_FORMULA_QUIZ_ITEMS}
